# configs/config_lm.yaml

optimization:
  method: "lm"          # Levenberg-Marquardt algorithm
  loss: "linear"        # 'lm' does not support bounds; use 'linear' loss
  initial_guess: [0.01, 0.5, 0.5, 0.5, 0.5, 0.3, 0.5, .1, 0.5]  # Initial guesses for theta0 to theta6, w0, m

plot:
  save: true
  format: "png"

output:
  directory: "results"

