# configs/config_dogbox.yaml

optimization:
  method: "dogbox"     # Dogleg algorithm
  loss: "soft_l1"      # Choose from 'linear', 'soft_l1', 'huber', 'cauchy', 'arctan'
  initial_guess: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]  # Initial guesses for theta0 to theta6, w0, m

plot:
  save: true
  format: "png"

output:
  directory: "results"

